### PR TITLE
Add quote and order update streaming

### PR DESCRIPTION
**Pull request by b0b5h4rp13**
Correct minor issues with screener
Add class StreamConn which does websocket streaming.
Add instructions to the readme
Added an __init__.py to let it live in a folder
now needs paho-mqtt >=1.5 from pypy
Enjoy :)

### CODE REVIEW

**Comment by tedchou12** [comment]
@b0b5h4rp13 
Thanks Bob! Sorry for the delay.
I made some changes to it, since there might be some not using the Streaming.
I have added the instructions to the Wiki.
Made StreamConn class a separate file.
I got it working fine, but I am not sure how to use it, seems quite intriguing, I will study it when I get some more time.

**Comment by b0b5h4rp13** [comment]
Roger, not a problem. Just offering what I need to make the morning momentum trading bot work right using paper trading at first

**Comment by b0b5h4rp13** [comment]
you should remove the did.bin from the archive, it will cause people to reuse the dame device id, resulting in crazyness if they use streaming quotes

**Comment by tedchou12** [comment]
Thank you! That's true.
Let me add that to the gitignore locally.

**Pull request merged**
